[package]
name = "homie-controller"
version = "0.5.1"
authors = ["Andrew Walbran <qwandor@google.com>", "David Laban <alsuren@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A library for creating controllers to talk to devices implementing the Homie convention for MQTT."
repository = "https://github.com/alsuren/mijia-homie/"
keywords = ["homie", "mqtt"]
categories = ["network-programming"]

[dependencies]
log = "0.4.17"
rumqttc = "0.12.0"
thiserror = "1.0.31"

[dev-dependencies]
async-channel = "1.6.1"
futures = "0.3.21"
homie-device = { version = "0.6.1", path = "../homie-device" }
pretty_env_logger = "0.4.0"
rumqttd = "0.11.0"
rumqttlog = "0.9.0"
# TODO: Remove "io-util" once a new version of rumqttc is released which fixes
# https://github.com/bytebeamio/rumqtt/issues/294.
tokio = { version = "1.19.2", features = ["io-util", "macros", "rt", "rt-multi-thread", "time"] }
